### ISSUE TITLE
host_path: '.' always defaults to $HOME?

### ISSUE THREAD

**Issue by tcwan** [matthieudelaro/nut#33] opened 2018-01-23 03:21 UTC
I've been looking for a way to manage cross-compilers using Docker, and I found `nut` just today. I've built nut from source using the directions in the Readme.

I'm trying to understand how to specify $PWD so that I can do the following:
```
$ cd $PROJECT_DIR
$ nut build
```

In the nut.yml file, I followed the example:
```
syntax_version: "7"
volumes: # declare folders to mount in the container
  project: # give each folder any name that you like
    host_path: .               # this folder (from your computer) will be mounted as
    container_path: /src       # this folder (in the container)
```

However, on my macOSX High Sierra environment, `.` always defaults to $HOME, it does not adopt $PWD.

Is this a bug or am I doing something wrong?

**Comment by matthieudelaro** [comment] 2018-10-04 08:34
Hi tcwan,

I didn't upgrade to High Sierra yet, I'm still on Sierra. I did a test with your nut.yml thou:
```
/tmp/testNut$ nut --exec "ls /src -lah"
total 8
drwxr-xr-x    3 root     root         102 Oct  4 10:25 .
drwxr-xr-x    1 root     root        4.0K Oct  4 10:26 ..
-rw-r--r--    1 root     root         296 Oct  4 10:22 nut.yml
/tmp/testNut$ cat nut.yml 
syntax_version: "7"
docker_image: alpine
volumes: # declare folders to mount in the container
  project: # give each folder any name that you like
    host_path: .               # this folder (from your computer) will be mounted as
    container_path: /src       # this folder (in the container)
/tmp/testNut$ ls -lah
total 8
drwxr-xr-x   3 matthieu  wheel   102B  4 Oct 10:25 ./
drwxrwxrwt  14 root      wheel   476B  4 Oct 10:28 ../
-rw-r--r--   1 matthieu  wheel   296B  4 Oct 10:22 nut.yml
```

That seems to be in order.  Do you experience as I with the exact same file, or does it reproduce your issue?

Also, what happens with the following nut.yml ?
```
/tmp/testNut$ cat nut.yml
syntax_version: "7"
docker_image: alpine
work_in_project_folder_as: /src
/tmp/testNut$ nut --exec "ls -lah"
total 8
drwxr-xr-x    3 root     root         102 Oct  4 10:25 .
drwxr-xr-x    1 root     root        4.0K Oct  4 10:31 ..
-rw-r--r--    1 root     root          73 Oct  4 10:29 nut.yml
```

work_in_project_folder_as is a handy nut.yml file option which will mount the folder of the project (where nut.yml is located) to the given location inside the container. It will also set the working directory to this location. This is equivalent to container_working_directory + volume. I'm eager to see if this works any better for you

**Comment by tcwan** [comment] 2018-10-15 00:04
Hi,
I apologize for not replying sooner, I didn't check my github for a while due to other commitments.

By default, my nut.yml is kept in $HOME. I revised my nut.yml to use the `work_in_project_folder_as: /src` option, and removed all the volume definitions.
I still see the same issue where only $HOME contents is displayed, using `nut --exec "ls /src -lah"`

I then removed the default nut.yml in $HOME, and copied your version of nut.yml to the $PROJECT folder. When I run `nut --exec "ls /src -lah"` I now see the contents of the $PROJECT folder.

However, when I run `nut --exec "ls . -lah"` inside a $PROJECT subdirectory folder, it will still display the contents of the $PROJECT folder.

From my experiments, I think nut's $CWD is anchored in the folder containing the nut.yml file. the $CWD is always referenced from that location.

Note: In my project folder, I have two subdirectories, src and build. I changed directory to the src subdirectory before starting the `nut --exec` tests.

```
TCWiMac:EV3 tcmac$ ls -Ralt
total 32
-rw-r--r--   1 tcmac  staff    75 15 Oct 08:00 nut.yml
drwxr-xr-x   3 tcmac  staff   102 15 Oct 07:59 build/
drwxr-xr-x   3 tcmac  staff   102 15 Oct 07:59 src/
drwxr-xr-x   6 tcmac  staff   204 15 Oct 07:55 ./
drwxr-xr-x  60 tcmac  staff  2040  6 Sep 10:04 ../
-rw-r--r--@  1 tcmac  staff  8196 19 Jul 14:09 .DS_Store

./build:
total 0
drwxr-xr-x  3 tcmac  staff  102 15 Oct 07:59 ./
-rw-r--r--  1 tcmac  staff    0 15 Oct 07:59 another.txt
drwxr-xr-x  6 tcmac  staff  204 15 Oct 07:55 ../

./src:
total 0
drwxr-xr-x  3 tcmac  staff  102 15 Oct 07:59 ./
-rw-r--r--  1 tcmac  staff    0 15 Oct 07:59 temp.txt
drwxr-xr-x  6 tcmac  staff  204 15 Oct 07:55 ../
TCWiMac:EV3 tcmac$ cat nut.yml 
syntax_version: "7"
docker_image: ev3cross
work_in_project_folder_as: /src
TCWiMac:EV3 tcmac$ cd src
TCWiMac:src tcmac$ nut --exec "ls /src -lah"
total 20K
drwxr-xr-x 6 compiler compiler  204 Oct 15 07:55 .
drwxr-xr-x 1 root     root     4.0K Oct 15 08:01 ..
-rw-r--r-- 1 compiler compiler 8.1K Jul 19 14:09 .DS_Store
drwxr-xr-x 3 compiler compiler  102 Oct 15 07:59 build
-rw-r--r-- 1 compiler compiler   75 Oct 15 08:00 nut.yml
drwxr-xr-x 3 compiler compiler  102 Oct 15 07:59 src
TCWiMac:src tcmac$ nut --exec "ls . -lah"
total 20K
drwxr-xr-x 6 compiler compiler  204 Oct 15 07:55 .
drwxr-xr-x 1 root     root     4.0K Oct 15 08:01 ..
-rw-r--r-- 1 compiler compiler 8.1K Jul 19 14:09 .DS_Store
drwxr-xr-x 3 compiler compiler  102 Oct 15 07:59 build
-rw-r--r-- 1 compiler compiler   75 Oct 15 08:00 nut.yml
drwxr-xr-x 3 compiler compiler  102 Oct 15 07:59 src
TCWiMac:src tcmac$ nut --exec "ls build -lah"
total 0
drwxr-xr-x 3 compiler compiler 102 Oct 15 07:59 .
drwxr-xr-x 6 compiler compiler 204 Oct 15 07:55 ..
-rw-r--r-- 1 compiler compiler   0 Oct 15 07:59 another.txt
TCWiMac:src tcmac$ nut --exec "ls src -lah"
total 0
drwxr-xr-x 3 compiler compiler 102 Oct 15 07:59 .
drwxr-xr-x 6 compiler compiler 204 Oct 15 07:55 ..
-rw-r--r-- 1 compiler compiler   0 Oct 15 07:59 temp.txt
TCWiMac:src tcmac$ 
```

**Comment by matthieudelaro** [comment] 2018-10-15 11:41
Maybe I'm missing something from your explanations, but this all seems like normal behaviour.
One goal of Nut is to provide dev/run environments in containers, for a given project, agnostic from your platform. This implies that it doesn't inherit from you environment variables, and considers the location of nut.yml as the reference path.

Since you may want to run nut from a subdirectory of the folder where your nut.yml lies, Nut looks for nut.yml in the current directory, and then in parent directories if need be. So, to answer your main question, '.'  in Nut doesn't not always default to $HOME, but to the directory where nut.yml lies.

In your case, declaring nut.yml makes '.' default to your $HOME folder. Such declaration seems like an attempt to reuse configuration in several projects : in this case, I advise you use one of the following options instead:
```
based_on: # configuration can be inherited from:
  github: matthieudelaro/nutfiles/golang1.6 # a GitHub repository
  nut_file_path: /Users/tcwan/nut.yml # a local file, but I advise you to move it to another folder, in such a way that Nut will fire an error if you forgot to create a nut.yml in your project folder
  # Note that you can inherite either from GitHub or from a file, not both.
```

As for your example, let's comment it inline to better explain what seems to happen:
```
TCWiMac:EV3 tcmac$ cat nut.yml 
syntax_version: "7"
docker_image: ev3cross
work_in_project_folder_as: /src      # this mount current folder as /src and selects /src as container working directory
TCWiMac:EV3 tcmac$ cd src
TCWiMac:src tcmac$ nut --exec "ls /src -lah"
total 20K
drwxr-xr-x 6 compiler compiler  204 Oct 15 07:55 .
drwxr-xr-x 1 root     root     4.0K Oct 15 08:01 ..
-rw-r--r-- 1 compiler compiler 8.1K Jul 19 14:09 .DS_Store
drwxr-xr-x 3 compiler compiler  102 Oct 15 07:59 build
-rw-r--r-- 1 compiler compiler   75 Oct 15 08:00 nut.yml
drwxr-xr-x 3 compiler compiler  102 Oct 15 07:59 src
TCWiMac:src tcmac$ nut --exec "ls . -lah"    # $PWD is currently /src, which explains that the command outputs the same as the previous one
total 20K
drwxr-xr-x 6 compiler compiler  204 Oct 15 07:55 .
drwxr-xr-x 1 root     root     4.0K Oct 15 08:01 ..
-rw-r--r-- 1 compiler compiler 8.1K Jul 19 14:09 .DS_Store
drwxr-xr-x 3 compiler compiler  102 Oct 15 07:59 build
-rw-r--r-- 1 compiler compiler   75 Oct 15 08:00 nut.yml
drwxr-xr-x 3 compiler compiler  102 Oct 15 07:59 src
TCWiMac:src tcmac$ nut --exec "ls build -lah"   # $PWD is currently /src
total 0
drwxr-xr-x 3 compiler compiler 102 Oct 15 07:59 .
drwxr-xr-x 6 compiler compiler 204 Oct 15 07:55 ..
-rw-r--r-- 1 compiler compiler   0 Oct 15 07:59 another.txt
TCWiMac:src tcmac$ nut --exec "ls src -lah"   # $PWD is currently /src
total 0
drwxr-xr-x 3 compiler compiler 102 Oct 15 07:59 .
drwxr-xr-x 6 compiler compiler 204 Oct 15 07:55 ..
-rw-r--r-- 1 compiler compiler   0 Oct 15 07:59 temp.txt
TCWiMac:src tcmac$ 
```

Does that answer your questions? Seems like there isn't any issue so I will close it, but don't hesitate to ask more details (or even to show me what I may have misunderstood)

**Closed by matthieudelaro** 2018-10-15 11:41 UTC

**Comment by tcwan** [comment] 2018-10-16 00:49
Thanks for the help. I was under the impression that nut.yml is a global configuration file. Guess I will maintain separate nut.ymls for each project as needed.
